baseURL = "https://www.setinhash.com"  # Replace with your URL
languageCode = "en-us"
title = ""
theme = "noteworthy"
enableRobotsTXT = true
paginate = 20 # Set the number of posts to show before overflowing to the next page.
summaryLength = 70 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

disableKinds = ["RSS"]
enableEmoji = true

[permalinks]
  posts = "/posts/:filename/"
  replies = "/posts/:filename/"

[taxonomies]
  channel = "channels"
  feed = "feeds"
  thread = "threads"


# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = false
    hardWraps = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	# description = ""

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

# Menu links along the sidebar navigation.


[[menu.main]]
	identifier = "new"
	name = "%"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "channels"
	name = "#"
	url = "/channels/"
	weight = 2

[[menu.main]]
	identifier = "feeds"
	name = "@"
	url = "/feeds/"
	weight = 3

[[menu.main]]
	identifier = "about"
	name = "?"
	url = "/about/"
	weight = 4 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


# [[menu.main]]
# 	name = "Archives"
# 	identifier = "archives"
# 	url = "/archives/"
# 	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
